// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PGLaw.Infra.Data.Contratos.Context;
using System;

namespace PGLaw.Infra.Data.Contratos.Migrations
{
    [DbContext(typeof(ContratoContext))]
    [Migration("20180516011431_addTabelsTipos3")]
    partial class addTabelsTipos3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PGLaw.Domain.Contratos.Contratos.Entitties.Contrato", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("Ativo");

                    b.Property<bool>("ClausulaJuros");

                    b.Property<bool>("ClausulaMulta");

                    b.Property<Guid>("ClienteId");

                    b.Property<DateTime>("DataAssinatura");

                    b.Property<DateTime>("DataVencimento");

                    b.Property<Guid>("GerenciaId");

                    b.Property<Guid>("IndiceReajusteId");

                    b.Property<string>("Juros");

                    b.Property<string>("Multa");

                    b.Property<string>("Objeto");

                    b.Property<string>("RazaoSocial");

                    b.Property<Guid>("TipoId");

                    b.Property<Guid>("VigenciaId");

                    b.HasKey("Id");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("PGLaw.Domain.Contratos.Contratos.ValueObjects.Gerencia", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Gerencia");
                });

            modelBuilder.Entity("PGLaw.Domain.Contratos.Contratos.ValueObjects.IndiceReajuste", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("IndiceReajuste");
                });

            modelBuilder.Entity("PGLaw.Domain.Contratos.Contratos.ValueObjects.Tipo", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("PGLaw.Domain.Contratos.Contratos.ValueObjects.Vigencia", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Vigencia");
                });
#pragma warning restore 612, 618
        }
    }
}
