// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PGLaw.Infra.Data.Sistema.Context;
using System;

namespace PGLaw.Infra.Data.Sistema.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20180308211600_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ordem");

                    b.Property<string>("Titulo");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.NivelDeAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detalhes");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("NivelDeAcesso");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Relashionships.MenuNivelDeAcesso", b =>
                {
                    b.Property<Guid>("MenuId");

                    b.Property<Guid>("NivelDeAcessoId");

                    b.HasKey("MenuId", "NivelDeAcessoId");

                    b.HasIndex("NivelDeAcessoId");

                    b.ToTable("MenuNivelDeAcesso");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Relashionships.MenuNivelDeAcesso", b =>
                {
                    b.HasOne("PGLaw.Domain.Sistema.Entitties.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PGLaw.Domain.Sistema.Entitties.NivelDeAcesso", "NivelDeAcesso")
                        .WithMany("MenuNivelDeAcesso")
                        .HasForeignKey("NivelDeAcessoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
