// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PGLaw.Infra.Cross.Core.Enums;
using PGLaw.Infra.Data.Sistema.Context;
using System;

namespace PGLaw.Infra.Data.Sistema.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20180313192520_Atualização de Usuario e Nivel de Acesso")]
    partial class AtualizaçãodeUsuarioeNiveldeAcesso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MenuPaiId");

                    b.Property<string>("Ordem");

                    b.Property<string>("Titulo");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("MenuPaiId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.NivelDeAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detalhes");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("NiveisDeAcessos");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Relashionships.MenuNivelDeAcesso", b =>
                {
                    b.Property<Guid>("MenuId");

                    b.Property<Guid>("NivelDeAcessoId");

                    b.HasKey("MenuId", "NivelDeAcessoId");

                    b.HasIndex("NivelDeAcessoId");

                    b.ToTable("MenuNivelDeAcesso");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Relashionships.UsuarioNivelDeAcesso", b =>
                {
                    b.Property<Guid>("UsuarioId");

                    b.Property<Guid>("NivelDeAcessoId");

                    b.Property<Guid?>("UsuarioId1");

                    b.HasKey("UsuarioId", "NivelDeAcessoId");

                    b.HasIndex("NivelDeAcessoId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("UsuarioNivelDeAcesso");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcessoDiasDaSemana");

                    b.Property<bool>("Ativo");

                    b.Property<string>("Email");

                    b.Property<bool>("TrocarSenha");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Menu", b =>
                {
                    b.HasOne("PGLaw.Domain.Sistema.Entitties.Menu", "MenuPai")
                        .WithMany("MenusFilhos")
                        .HasForeignKey("MenuPaiId");
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Relashionships.MenuNivelDeAcesso", b =>
                {
                    b.HasOne("PGLaw.Domain.Sistema.Entitties.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PGLaw.Domain.Sistema.Entitties.NivelDeAcesso", "NivelDeAcesso")
                        .WithMany("MenuNivelDeAcesso")
                        .HasForeignKey("NivelDeAcessoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PGLaw.Domain.Sistema.Entitties.Relashionships.UsuarioNivelDeAcesso", b =>
                {
                    b.HasOne("PGLaw.Domain.Sistema.Entitties.NivelDeAcesso", "NivelDeAcesso")
                        .WithMany()
                        .HasForeignKey("NivelDeAcessoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PGLaw.Domain.Sistema.Entitties.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PGLaw.Domain.Sistema.Entitties.Usuario")
                        .WithMany("UsuarioNiveisDeAcesso")
                        .HasForeignKey("UsuarioId1");
                });
#pragma warning restore 612, 618
        }
    }
}
